/**
 * exoskeleton/hooks.ts — Enforcement Guard: pre-commit hooks and integrity checks.
 *
 * Invariants enforced mechanically never need to be remembered.
 * This module provides:
 * - Secret scanning (pattern-based)
 * - Checklist freshness gate (section-hash, not timestamp)
 * - Budget lint (spine.md ≤500 tok, ratchet ≤8k tok)
 * - Protected path enforcement
 * - Hook installer (writes standalone Node pre-commit script)
 */

import * as vscode from 'vscode';
import * as fs from 'fs';
import * as path from 'path';
import {
    SECRET_PATTERNS,
    PROTECTED_PATHS,
    SPECIALIST_INDEX_BUDGET_TOKENS,
    RATCHET_BUDGET_TOKENS,
} from './constants';
import {
    estimateTokens,
    isProtectedPath,
    redactSecrets,
} from './utils';

export interface ScanResult {
    passed: boolean;
    findings: string[];
    redactedFiles: string[];
}

/**
 * Scan staged file contents for secrets using pattern matching.
 * This is a first line of defense — not a replacement for gitleaks.
 */
export function scanForSecrets(stagedContents: { path: string; content: string }[]): ScanResult {
    const findings: string[] = [];
    const redactedFiles: string[] = [];

    for (const file of stagedContents) {
        for (const pattern of SECRET_PATTERNS) {
            // Reset regex lastIndex for global patterns
            pattern.lastIndex = 0;
            const match = pattern.exec(file.content);
            if (match) {
                findings.push(`${file.path}: potential secret detected (${match[0].slice(0, 8)}...)`);
                redactedFiles.push(file.path);
            }
        }
    }

    return {
        passed: findings.length === 0,
        findings,
        redactedFiles,
    };
}

/**
 * Check if any staged files are in protected paths.
 */
export function checkProtectedPaths(stagedPaths: string[]): string[] {
    return stagedPaths.filter(p => isProtectedPath(p, PROTECTED_PATHS));
}

/**
 * Budget lint — check that the specialist index and ratchet stay within token limits.
 */
export function budgetLint(spineMdContent: string, ratchetContent: string[]): { passed: boolean; findings: string[] } {
    const findings: string[] = [];

    const spineTokens = estimateTokens(spineMdContent);
    if (spineTokens > SPECIALIST_INDEX_BUDGET_TOKENS) {
        findings.push(`Specialist index exceeds budget: ${spineTokens} tokens > ${SPECIALIST_INDEX_BUDGET_TOKENS} (chars/4)`);
    }

    const totalRatchetTokens = ratchetContent.reduce((sum, content) => sum + estimateTokens(content), 0);
    if (totalRatchetTokens > RATCHET_BUDGET_TOKENS) {
        findings.push(`Knowledge ratchet exceeds budget: ${totalRatchetTokens} tokens > ${RATCHET_BUDGET_TOKENS} (chars/4)`);
    }

    return {
        passed: findings.length === 0,
        findings,
    };
}

/**
 * Generate the standalone pre-commit hook script.
 * This is a Node script that runs outside the extension host (no vscode import).
 */
export function generatePreCommitScript(): string {
    return `#!/usr/bin/env node
/**
 * Harmony Exoskeleton — Pre-commit Enforcement Hook
 * Generated by harmony_guard. Do not edit manually.
 * Runs secret scanning, protected-path checks, and budget lint.
 */
'use strict';
const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');

const SECRET_PATTERNS = [
    /(?:sk-)[a-zA-Z0-9]{20,}/g,
    /(?:sk-kimi-)[a-zA-Z0-9]{20,}/g,
    /(?:ghp_)[a-zA-Z0-9]{36,}/g,
    /(?:gho_)[a-zA-Z0-9]{36,}/g,
    /(?:AKIA)[A-Z0-9]{16}/g,
    /(?:xoxb-)[a-zA-Z0-9-]+/g,
    /(?:AIza)[a-zA-Z0-9_-]{35}/g,
];
const PROTECTED_PATHS = [
    '.harmony/hooks/',
    '.harmony/oracle/',
    '.harmony/spine.json',
    '.harmony/routes.json',
    '.harmony/contracts.json',
    '.harmony/gitleaksignore',
    '.harmony/checksums.sha256',
];
let failures = [];

// Get staged files
let stagedFiles = [];
try {
    stagedFiles = execSync('git diff --cached --name-only', { encoding: 'utf-8' }).trim().split('\\n').filter(Boolean);
} catch (e) {
    process.exit(0); // Not a git repo or no staged files
}

// 1. Secret scan
for (const file of stagedFiles) {
    if (!fs.existsSync(file)) continue;
    const content = fs.readFileSync(file, 'utf-8');
    for (const pattern of SECRET_PATTERNS) {
        pattern.lastIndex = 0;
        const match = pattern.exec(content);
        if (match) {
            failures.push('SECRET: ' + file + ': potential secret (' + match[0].slice(0, 8) + '...)');
        }
    }
}

// 2. Protected path check
for (const file of stagedFiles) {
    const normalized = file.replace(/\\\\\\\\/g, '/').toLowerCase();
    for (const pp of PROTECTED_PATHS) {
        if (normalized.includes(pp)) {
            failures.push('PROTECTED: ' + file + ': protected path requires operator approval');
        }
    }
}

// 3. .env boundary check
for (const file of stagedFiles) {
    if (/^\\.env(?!\\.example)/i.test(path.basename(file))) {
        failures.push('ENV: ' + file + ': .env files must not be committed');
    }
}

// Report
if (failures.length > 0) {
    console.error('\\n🛡️ Harmony Exoskeleton pre-commit hook blocked this commit:\\n');
    for (const f of failures) console.error('  ❌ ' + f);
    console.error('\\nFix the issues above, or use PHASE_GATE_SKIP=1 to bypass (logged to LEDGER).\\n');
    process.exit(1);
}
process.exit(0);
`;
}

/**
 * Install the pre-commit hook into the workspace's git repository.
 * Uses git config core.hooksPath to set a dedicated hooks directory.
 */
export async function installPreCommitHook(): Promise<{ success: boolean; message: string }> {
    const root = vscode.workspace.workspaceFolders?.[0]?.uri.fsPath ?? '';
    if (!root) {
        return { success: false, message: 'No workspace folder open.' };
    }

    const gitDir = path.join(root, '.git');
    if (!fs.existsSync(gitDir)) {
        return { success: false, message: 'Not a git repository.' };
    }

    // Create .harmony/hooks directory
    const hooksDir = path.join(root, '.harmony', 'hooks');
    if (!fs.existsSync(hooksDir)) {
        fs.mkdirSync(hooksDir, { recursive: true });
    }

    // Write the pre-commit script
    const hookPath = path.join(hooksDir, 'pre-commit');
    fs.writeFileSync(hookPath, generatePreCommitScript(), 'utf-8');

    // Make executable on Unix
    if (process.platform !== 'win32') {
        fs.chmodSync(hookPath, 0o755);
    }

    // Set git hooksPath
    try {
        const { execSync } = require('child_process');
        execSync('git config core.hooksPath .harmony/hooks', { cwd: root });
    } catch {
        return { success: false, message: 'Failed to set git hooksPath.' };
    }

    return {
        success: true,
        message: 'Pre-commit hook installed at .harmony/hooks/pre-commit. Git hooksPath set to .harmony/hooks.',
    };
}
